dataset_mode: raw

prophet_params:
  seasonality_mode: additive
  yearly_seasonality: false
  weekly_seasonality: true
  daily_seasonality: false
  changepoint_prior_scale: 0.05
  seasonality_prior_scale: 8.0

tune_grid:
  changepoint_prior_scale: [0.02, 0.05, 0.1]
  seasonality_prior_scale: [4.0, 8.0, 12.0]
