raw_csv: "datasets/original_data.csv"
time_col: "AGGREGATE_DATE"
target_col: "DELIVERED_VALUE"
id_col: "METER_UI"
freq: "D"
aggregate_freq: "D"
aggregate_per_entity: true
entity_aggregation_method: sum
train_end: "2023-02-24"
val_end: "2023-03-24"
test_end: "2023-04-24"
clip_low_pct: 0.5
clip_high_pct: 99.5
exclude_ids:
  - "34"
aggregation_method: mean
special_days:
  school_holidays:
    - start: "2022-07-02"
      end: "2022-07-17"
    - start: "2022-09-24"
      end: "2022-10-09"
    - start: "2022-12-15"
      end: "2023-02-01"
    - start: "2023-04-07"
      end: "2023-04-23"
  public_holidays:
    - "2022-04-25"
    - "2022-06-06"
    - "2022-09-22"
    - "2022-09-26"
    - "2022-12-25"
    - "2022-12-26"
    - "2022-12-27"
    - "2023-01-01"
    - "2023-01-02"
    - "2023-01-26"
    - "2023-03-06"
    - "2023-04-07"
    - "2023-04-09"
    - "2023-04-10"
